### ISSUE TITLE
Passes the correct Password without finding it

### ISSUE THREAD

**Issue by LinGtriX** [jeanluc162/ZipCrackNetCore#3]
[test.zip](https://github.com/jeanluc162/ZipCrackNetCore/files/4567641/test.zip)
searching for the password "zyx" from 1 to 5 with output paramenter skips the correct password sometimes.
(./ZipCrackNetCore /home/pi/ZipCrack/test.zip abcdefghijklmnopqrstuvwxyz 1 5 output)
![ZipCrackTest](https://user-images.githubusercontent.com/61557348/80863614-df194f80-8c7d-11ea-8111-cc73f334a826.png)

Second try finds correct password, this time searching between 1 and 3 without output

**Comment by jeanluc162** [comment]
Password seems to get determined correctly, however the other threads are not killed fast enough and continue to output their tries after the password has already been printed. This leads to it not being visible upon termination of the program without scrolling back up.

![zyx](https://user-images.githubusercontent.com/12240422/80864452-0fafb800-8c83-11ea-9abe-d45b03c0dc58.PNG)

**Comment by jeanluc162** [comment]
Issue has been resolved by moving the Output to a seperate thread.
